server:
  port: 8181
  context-path: /open-cp-web
spring:
  application:
    name: open-cp-web
  cloud:
    consul:
      host: 192.168.151.49
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
        health-check-path: ${server.context-path}/health
        instance-id: ${spring.application.name}-${spring.cloud.client.ipAddress}